on:
  push:
    branches:
      - main
  pull_request:
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: go test ./...
